spring:
  data:
    mongodb:
      database: service-discovery
      uri: ${MONGODB_URI}

graphql:
  packages:
    - dev.marfien.servicediscovery.registry.schema
    - dev.marfien.servicediscovery.registry.subscription
    - dev.marfien.servicediscovery.registry.model