spring:
  data:
    mongodb:
      database: service-discovery
      uri: mongodb+srv://root:OzSSQymCQZZd86tf@service-discovery.nargo5k.mongodb.net/?retryWrites=true&w=majority

graphql:
  packages:
    - dev.marfien.servicediscovery.registry.schema
    - dev.marfien.servicediscovery.registry.subscription
    - dev.marfien.servicediscovery.registry.model